* 題目：
  * 【基礎08】
     1. 【簡答題】請問 Pandas 套件最主要的貢獻是什麼？
     2. 提供的資料集，印出他們的屬性分別為何？ （屬性：shape、size、values、index、columns、dtypes、len）
  * 【基礎09】
     1. 請建立類似提供結果的 DataFrame
     2. 請問如果現在有一個 DataFrame 如下，請問資料在 Python 中可能長怎樣？
     3. 假設你想知道每個 weekday 的平均 visitor 數量，可以怎麼做？

In [ ]:
import numpy as np
import pandas as pd
print( 'Numpy 版本: ', np.__version__ )
print( 'Pandas 版本: ', pd.__version__ )

Numpy 版本:  1.19.2
Pandas 版本:  1.1.3

* 【基礎08】

In [ ]:
# 1. 【簡答題】請問 Pandas 套件最主要的貢獻是什麼？

Ans：為 Python 提供高性能的數據結構和數據分析工具，也對現有的資料格式有不錯的銜接性。 提供了快速高效的 DataFrame 結構。 廣泛地在學術傑與商業領域中使用，包括金融，神經科學，經濟學，統計學，廣告，Web分析等。 對於資料格式有高度的銜接性，包含 CSV、Excel 或資料庫（SQL）皆能提供彈性的讀寫工具。

In [ ]:
# 2. 提供的資料集，印出他們的屬性分別為何？ （屬性：shape、size、values、index、columns、dtypes、len）
df = pd.read_csv('https://raw.githubusercontent.com/MachineLearningLiuMing/scikit-learn-primer-guide/master/Data.csv')
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
print('shape: ', df.shape)
print('---'*4)
print('size: ', df.size)
print('---'*4)
print('values: ', df.values)
print('---'*4)
print('index: ', df.index)
print('---'*4)
print('columns: ', df.columns)
print('---'*4)
print('dtypes: ', df.dtypes)
print('---'*4)
print('len: ', len(df))

shape:  (10, 4)
------------
size:  40
------------
values:  [['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]
------------
index:  RangeIndex(start=0, stop=10, step=1)
------------
columns:  Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')
------------
dtypes:  Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object
------------
len:  10

* 【基礎09】

In [ ]:
# 1. 請建立類似提供結果的 DataFrame：

# 1. Create a DataFrame `fruits` that looks like left:

df = pd.DataFrame([[30, 21]], columns=['Apples', 'Bananas'])
print(df)


# 2. Create a dataframe `fruit_sales` that matches the diagram right:

df = pd.DataFrame([[30, 21], [41, 34]], columns=['Apples', 'Bananas'], index=['2017 Sales', '2018 Sales'])
print(df)

   Apples  Bananas
0      30       21
            Apples  Bananas
2017 Sales      30       21
2018 Sales      41       34

In [ ]:
# 請問如果現在有一個 DataFrame 如下，請問資料在 Python 中可能長怎樣？
d = [
    ['Austin', 139, 'Sun'],
    ['Dallas', 237, 'Sun'],
    ['Austin', 139, 'Mon'],
    ['Dallas', 456, 'Mon'],
]

df = pd.DataFrame(d, columns=['city', 'visitor', 'weekday'])
df

     city  visitor weekday
0  Austin      139     Sun
1  Dallas      237     Sun
2  Austin      139     Mon
3  Dallas      456     Mon

In [ ]:
for day in set(df['weekday']):
    print(day, df[df['weekday'] == day]['visitor'].mean())

Mon 297.5
Sun 188.0